jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: '11'
    - continue-on-error: true
      name: Build with Maven
      run: xvfb-run mvn -B license:check
name: Check license header
on:
  repository_dispatch:
    types: trigger-ga___check.yml
