jobs:
  deploy:
    name: Deploy Snapshot
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: master
    - continue-on-error: true
      name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 11
        server-id: sonatype-nexus-snapshots
        server-password: MAVEN_CENTRAL_TOKEN
        server-username: MAVEN_USERNAME
    - continue-on-error: true
      env:
        MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_PASSWORD }}
        MAVEN_USERNAME: ${{ secrets.MAVEN_USER }}
      name: Deploy to Maven Central
      run: xvfb-run mvn -B deploy
name: Deploy Snapshot
on:
  repository_dispatch:
    types: trigger-ga___deploy_snapshot.yml
